apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortex.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.cortex.port }}
    targetPort: {{ .Values.cortex.port }}
    nodePort: {{ .Values.cortex.nodePort }}
  selector:
    app: cortex