apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortex.pvc.jobDataPvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.cortex.pvc.storageSize }}