apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: elasticsearch-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.elasticsearch.matchLabels.app }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Values.cortex.matchLabels.app }}
      ports:
        - protocol: TCP
          port: {{ .Values.elasticsearch.port }}