apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
  selector:
    app: {{ .Values.elasticsearch.matchLabels.app }}