apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.targetPort }}
  selector:
    app: elasticsearch