apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cortex.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.cortex.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.cortex.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortex.matchLabels.app }}
    spec:
      containers:
      - name: {{ .Values.cortex.name }}
        image: {{ .Values.cortex.image }}
        ports:
        - containerPort: {{ .Values.cortex.port }}
        resources:
          {{ toYaml .Values.cortex.resources | nindent 10 }}
        env:
          {{ toYaml .Values.cortex.env | nindent 10 }}
        livenessProbe:
          {{ toYaml .Values.cortex.livenessProbe | nindent 10 }}
        readinessProbe:
          {{ toYaml .Values.cortex.readinessProbe | nindent 10 }}
        volumeMounts:
          {{ toYaml .Values.cortex.volumeMounts | nindent 10 }}
      volumes:
        {{ toYaml .Values.cortex.volumes | nindent 8 }}
