apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.cortexReaderRole.roleBindingName }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: {{ .Values.cortexReaderRole.roleBindingUser }}
  apiGroup: {{ .Values.roleBindingApiGroup }}
roleRef:
  kind: Role
  name: {{ .Values.cortexReaderRole.name }}
  apiGroup: {{ .Values.roleBindingApiGroup }}
