apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortex.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ .Values.cortex.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.cortex.pvc.storageSize }}