apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.ingress.networkPolicyName }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.ingress.matchLabels.app }}
  policyTypes:
    {{ toYaml .Values.ingress.policyTypes | nindent 4 }}
  ingress:
    - from:
      {{ toYaml .Values.ingress.ingressFrom | nindent 6 }}
      ports:
        {{ toYaml .Values.ingress.ports | nindent 8}}
