{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
  labels:
    name: {{ .Values.monitoring.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"  # Ensures it runs early
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
