apiVersion: v2
name: cortex-chart
description: A Helm chart for Kubernetes to deploy Cortex and Elasticsearch
type: application
version: 0.4.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: 58.2.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
